### ISSUE TITLE
scrape_profiles does not have enough arguments

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap-daemon#137]
In oscap_helpers.py, function `scrape_profiles` has 5 arguments, but sometimes only 1st, 4th and 5th are given. The 2nd and 3rd argument are missing.

eg.
* https://github.com/OpenSCAP/openscap-daemon/blob/master/openscap_daemon/oscap_helpers.py#L145
* https://github.com/OpenSCAP/openscap-daemon/blob/master/openscap_daemon/oscap_helpers.py#L145

I think this will cause errors that not enough arguments were provided.

Please see https://github.com/OpenSCAP/openscap-daemon/blob/master/openscap_daemon/oscap_helpers.py

**Comment by mpreisler** [comment]
Yeah, good catch. https://github.com/OpenSCAP/openscap-daemon/pull/117 caused a regression in all use-cases of openscap-daemon except atomic scan, we need to fix this ASAP

the function no longer works for XCCDF files, only for datastreams
