### ISSUE TITLE
Add virtual machine scanning support

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap-daemon#15]
See `oscap_helpers.py`, function `get_evaluation_args`. This function figures out what daemon should call to evaluate given EvaluationSpec. Right now it supports `localhost`, `ssh://`, `docker-image://` and `docker-container://`. It calls `oscap`, `oscap-ssh` and `oscap-docker` respectively.

Since `oscap-vm` was merged into OpenSCAP recently it makes sense to add `vm-storage://` and `vm-domain://`.

**Comment by ybznek** [comment]
oscap-vm uses
```
$ oscap-vm image VM_STORAGE_IMAGE xccdf eval [options] INPUT_CONTENT
$ oscap-vm domain VM_DOMAIN xccdf eval [options] INPUT_CONTENT
```

Do you really want to use vm-storage:// instead of vm-image:// ?

**Comment by mpreisler** [comment]
You are right, let's use `vm-image`.
