### ISSUE TITLE
Automatically prune old results

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap-daemon#2]
Provide settings in tasks for how many results it should keep and/or how old results it should keep.

**Comment by mpreisler** [comment]
This is an important feature but at the same time we don't need it to be extremely flexible. We need to prune if there are too many results and we need to prune old results.

We need 2 options (heavily inspired by Jenkins):
`days-to-keep-results`
`max-results-to-keep`

**Comment by ybznek** [comment]
Do you have any recommendation, when to run "delete" routine?
- Have some suspended thread, which wake every day to check 'days-to-keep-results'
- After every scan check number of results - 'max-results-to-keep'

Do you know some more elegant solution?
@jan-cerny

**Comment by mpreisler** [comment]
Ideally we'd do the same thing we do when scheduling evaluations. Sleep until exactly the right time, then delete, sleep again until next event.

**Comment by mpreisler** [comment]
I have implemented old results pruning. Right now we prune if we have more results than some number. Old results are pruned first.

21e884e33169660d27bcb7930cc486bbdf3b1932
