### ISSUE TITLE
Unify the two configuration classes

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap-daemon#20]
The `image-scanner` and `openscap-daemon` projects merged together and due to time constraints we have made some compromises.

One of them is the existence of `applicationconfiguration` next to `config.Configuration`. The code should be refactored to only use the latter. The hard work of removing the singleton has already been done by @baude in #13. The next step is passing `self.system.config` in the dbus_daemon class instead of letting the `cve_scanner.Worker` construct the `applicationconfiguration` instance.

**Comment by mpreisler** [comment]
#93 will get rid of this.

**Comment by matejak** [comment]
This is a sortof duplicate of #93
