### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap-daemon#33]

**Comment by isimluk** [comment]
setup.py is now able to run in python3 and python2 mode. Please do not break that in the next upstream release.

F24 has (and F23 will shortly have) openscap-daemon in python3. Feel free to run the testing of the run-time in there.

**Comment by ybznek** [comment]
https://github.com/OpenSCAP/openscap-daemon/pull/41 Fix some atomic-scan related python3 issues.

**Comment by mpreisler** [comment]
AFAIK this has been solved. Reopen if necessary.

**Comment by ybznek** [comment]
I have fixed atomic-scan related use cases. We should test every daemon use case if there aren't some incompatibility issues.
