### ISSUE TITLE
Jenkins for this project

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap-daemon#44]
Is it practical to run current test suite in jenkins environment? What are the roadblocks?

**Comment by mpreisler** [comment]
We run it since the beginning, see https://jenkins.open-scap.org/job/openscap-daemon/

The test suite could use some improvements though...

**Comment by isimluk** [comment]
Ah, right. I am sorry, I haven't seen that.

Does it make sense to run the test suite on the pull-requests?

**Comment by mpreisler** [comment]
Certainly, the openscap jenkins bot has all rights necessary to do that.

**Comment by mpreisler** [comment]
https://jenkins.open-scap.org/job/openscap-daemon-pull-requests/
