### ISSUE TITLE
GObject.MainLoop, etc. is deprecated

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap-daemon#59]
On Fedora Rawhide(Python 3.5.1) I get 

```
/usr/bin/oscapd:66: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  loop = gobject.MainLoop()
```

If somebody fix that, he/she should also test if now version of code is working also with Python 2.*

**Comment by mpreisler** [comment]
5f5b8022e6063d5743491eb5916ad0a7a43a29fa Fixed
