### ISSUE TITLE
Missing configuration file

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap-daemon#68]
Our SPC based on F23 does not contain a config.ini file.
This command: `atomic install openscap/openscap-daemon-f23`
produces a message:
```Installation complete. Be sure to customize /etc/oscapd/config.ini as needed.```
However, no such file exists, so user can't customize it.
I think the message is little confusing then.

**Comment by mpreisler** [comment]
Agreed. We should inject a default pre-filled config.ini that people can customize.

**Comment by mpreisler** [comment]
https://github.com/OpenSCAP/openscap-daemon/commit/6600dc4a0551e74faf89c59c09d1a27f4a56940e will help with generating a suitable default config for user modification. The API was already there, I just exposed it.
