### ISSUE TITLE
How will we update SPC images on Docker hub?

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap-daemon#69]
Currently, we have on our account on Docker hub two images of super privileged containers. One of them is based on Fedora 23, second ins based on Fedora 22. See https://hub.docker.com/r/openscap/

I would like to ask all of you what are your opinions:
How often we will update these images?
Should they be updated each time after openscap-daemon is updated in Fedora? Or openscap itself?
Also when our Dockerfiles change in upstream?
Will we do it manually or should a script or a Jenkins job be created to automate the task?

Thank you.

**Comment by mpreisler** [comment]
As often as is necessary.

Each time daemon is updated. Each time openscap is updated and the update substantially changes behavior of the daemon.

Yes, when we change Dockerfiles and decide that it makes sense to update the images.

> Will we do it manually or should a script or a Jenkins job be created to automate the task?

Jenkins job would be great. Any input appreciated.

**Comment by jan-cerny** [comment]
@mpreisler Thank you very much for answer. It makes sense to me.

**Comment by isimluk** [comment]
What if there is an vulnerability in base image?

Perhaps, we should leave this open until we figure this out.
